name: Deploy to Firebase

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile_name: [Dockerfile]
        dockerfile_directory: [./]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install streamlit

      - name: Build Docker image
        run: docker build -t streamlit-app ${{ github.workspace }}/${{ matrix.dockerfile_directory }} -f ${{ github.workspace }}/${{ matrix.dockerfile_name }} --no-cache

      - name: Deploy to Firebase
        run: |
          curl -sL https://firebase.tools | bash
          export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          streamlit run app.py &
          firebase deploy --token "$FIREBASE_TOKEN"
